// 핀잇 픽 디자인 목록 (예시 샵 · 임의 이미지)
// category는 shop.dart의 shopCategories 중 하나
const List<Map<String, String>> pinitDesigns = [
  {
    'shop': '루나네일',
    'title': '시럽 마블 글리터 아트',
    'price': '55,000원',
    'category': '💅 네일',
    'keyword': '#시럽네일',
    'tag': '#이달의아트',
    'img': 'https://picsum.photos/300/300?random=1',
  },
  {
    'shop': '달콤케이크',
    'title': '빈티지 레터링 커스텀',
    'price': '38,000원',
    'category': '🎂 케이크',
    'keyword': '#생일케이크',
    'tag': '#레터링',
    'img': 'https://picsum.photos/300/300?random=2',
  },
  {
    'shop': '잉크타투',
    'title': '미니멀 라인 플라워',
    'price': '80,000원',
    'category': '🎨 타투',
    'keyword': '#미니타투',
    'tag': '#레터링',
    'img': 'https://picsum.photos/300/300?random=3',
  },
  {
    'shop': '글램래쉬',
    'title': '플랫모 뷰러 펌 세트',
    'price': '45,000원',
    'category': '👁️ 속눈썹',
    'keyword': '#속눈썹펌',
    'tag': '#이달의아트',
    'img': 'https://picsum.photos/300/300?random=4',
  },
  {
    'shop': '블룸아뜰리에',
    'title': '파스텔 튤립 꽃다발',
    'price': '35,000원',
    'category': '💐 꽃집',
    'keyword': '#꽃다발',
    'tag': '#생일케이크',
    'img': 'https://picsum.photos/300/300?random=5',
  },
  {
    'shop': '모모네일',
    'title': '자개 영롱 인스타 아트',
    'price': '60,000원',
    'category': '💅 네일',
    'keyword': '#시럽네일',
    'tag': '#이달의아트',
    'img': 'https://picsum.photos/300/300?random=6',
  },
  {
    'shop': '베이크미',
    'title': '캐릭터 입체 레터링 케이크',
    'price': '42,000원',
    'category': '🎂 케이크',
    'keyword': '#생일케이크',
    'tag': '#레터링',
    'img': 'https://picsum.photos/300/300?random=7',
  },
  {
    'shop': '네일디자인',
    'title': '치크 시럽 블러셔 아트',
    'price': '50,000원',
    'category': '💅 네일',
    'keyword': '#시럽네일',
    'tag': '#이달의아트',
    'img': 'https://picsum.photos/300/300?random=8',
  },
  {
    'shop': '타투스튜디오',
    'title': '감성 드로잉 미니타투',
    'price': '70,000원',
    'category': '🎨 타투',
    'keyword': '#미니타투',
    'tag': '#레터링',
    'img': 'https://picsum.photos/300/300?random=9',
  },
  {
    'shop': '뮤즈메이크업',
    'title': '웨딩 촬영 내추럴 메이크업',
    'price': '120,000원',
    'category': '💄 메이크업',
    'keyword': '#촬영메이크업',
    'tag': '#이달의아트',
    'img': 'https://picsum.photos/300/300?random=10',
  },
  {
    'shop': '글로우룸',
    'title': '졸업사진 데일리 메이크업',
    'price': '60,000원',
    'category': '💄 메이크업',
    'keyword': '#촬영메이크업',
    'tag': '#이달의아트',
    'img': 'https://picsum.photos/300/300?random=11',
  },
];
